# Generated by Django 3.2.9 on 2021-12-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_app', '0007_delete_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data wizyty')),
                ('visited', models.BooleanField(default=False, verbose_name='Wizyta wykonana')),
                ('proof_img', models.ImageField(upload_to='static/img/client/visits/', verbose_name='Zdjęcie apteki')),
                ('note', models.TextField(verbose_name='Notatka handlowca')),
                ('client_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.branch', verbose_name='Klient')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.employee', verbose_name='Handlowiec')),
            ],
        ),
    ]
