# Generated by Django 3.2.9 on 2021-12-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0004_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='proof_img',
            field=models.ImageField(null=True, upload_to='media/img/client/visits/', verbose_name='Zdjęcie apteki'),
        ),
    ]
