# Generated by Django 3.2.9 on 2021-12-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0005_alter_visit_proof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='note',
            field=models.CharField(max_length=256),
        ),
    ]
