# Generated by Django 3.2.9 on 2021-12-09 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='numer Partii')),
                ('ean', models.IntegerField(verbose_name='EAN')),
                ('expiration_date', models.DateField(verbose_name='data Przydatności do użycia')),
                ('netto', models.FloatField(verbose_name='cena netto')),
                ('vat', models.IntegerField(choices=[(1, '0.08'), (2, '0.23')], verbose_name='Starka podatku vat')),
                ('quantity', models.IntegerField(verbose_name='Ilość produktów')),
                ('is_active', models.BooleanField(default=True, verbose_name='W sprzedaży')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Adres korespondencyjny'), (2, 'Adres Rejestracyjny')], verbose_name='rodzaj adresu')),
                ('name_of_branch', models.CharField(max_length=60, null=True, verbose_name='Nazwa oddziału')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('province', models.CharField(max_length=16, null=True, verbose_name='Województwo')),
                ('city', models.CharField(max_length=20, verbose_name='Miejscowość')),
                ('street', models.CharField(max_length=64, verbose_name='Ulica')),
                ('building_number', models.CharField(max_length=8, verbose_name='Numer budynku')),
                ('apartment_number', models.CharField(max_length=8, null=True, verbose_name='Numer lokalu')),
                ('details', models.TextField(null=True, verbose_name='Szczególne informacje')),
                ('visit_days', models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], verbose_name='Wizyty w dni tygodnia')),
                ('visit_hour_from', models.TimeField(default='08:00', null=True, verbose_name='Wizyty od godziny')),
                ('visit_hour_to', models.TimeField(default='16:00', null=True, verbose_name='Wizyty do godziny')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Ilość')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.batch', verbose_name='Produkt i wariant')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(verbose_name='NIP')),
                ('company_name', models.CharField(max_length=128, verbose_name='Nazwa firmy')),
                ('logo', models.ImageField(null=True, upload_to='media/img/client/logo/')),
                ('regon', models.IntegerField(verbose_name='REGON')),
                ('krs', models.IntegerField(null=True, verbose_name='Numer KRS')),
                ('type', models.IntegerField(choices=[(1, 'Apteka sieciowa'), (2, 'Apteka rodzinna')], default=2, verbose_name='Rodzaj apteki')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Numer telefonu')),
                ('role', models.CharField(max_length=128, verbose_name='Stanowisko')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_app.employee', verbose_name='Przełożony')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Numer Faktury')),
                ('date', models.DateField(auto_now=True, verbose_name='Data wystawienia')),
                ('status', models.IntegerField(choices=[(1, 'Opłacona'), (2, 'Nieopłacona'), (3, 'Po terminie')], verbose_name='Status płatności')),
                ('payment_date', models.DateField(verbose_name='Termin płatności')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa produktu')),
                ('description', models.TextField(null=True, verbose_name='Opis')),
                ('active_substance', models.CharField(max_length=64, verbose_name='Substancja czynna')),
                ('is_active', models.BooleanField(default=True, verbose_name='W sprzedaży')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data wizyty')),
                ('visited', models.BooleanField(default=False, verbose_name='Wizyta wykonana')),
                ('proof_img', models.ImageField(upload_to='static/img/client/visits/', verbose_name='Zdjęcie apteki')),
                ('note', models.TextField(verbose_name='Notatka handlowca')),
                ('client_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.branch', verbose_name='Klient')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.employee', verbose_name='Handlowiec')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.IntegerField(verbose_name='Dawka')),
                ('unit', models.IntegerField(choices=[(1, 'mg'), (2, 'ml')], verbose_name='Jednostka(dawki)')),
                ('in_package', models.IntegerField(verbose_name='Ilość w Opakowaniu')),
                ('photo_main', models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie główne')),
                ('photo_2', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 2')),
                ('photo_3', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 3')),
                ('photo_4', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 4')),
                ('photo_5', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 5')),
                ('photo_6', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 6')),
                ('photo_7', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 7')),
                ('photo_8', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 8')),
                ('photo_9', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 9')),
                ('photo_10', models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 10')),
                ('next_delivery', models.DateField(null=True, verbose_name='Planowana data następnej dostawy')),
                ('is_active', models.BooleanField(default=True, verbose_name='W sprzedaży')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.product', verbose_name='Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, verbose_name='Numer zamówienia')),
                ('discount', models.IntegerField(verbose_name='Zniżka')),
                ('order_status', models.IntegerField(choices=[(1, 'Zamówienie przyjęte, oczekuje na weryfikację.'), (2, 'Zamówienie zmienione, oczekuje na potwierdzenie.'), (3, 'Potwierdzono zamówienie, przekazano do realizacji.'), (4, 'Skompletowane, oczekuje na kuriera.'), (5, 'Problem z zamówniem. Konieczność wyjaśnienia.'), (6, 'Przekazano kurierowi.'), (7, 'Oczekiwanie na płatność'), (8, 'Zakończone.')], default=1, verbose_name='Status zamówienia')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('batch', models.ManyToManyField(related_name='order', through='manager_app.Cart', to='manager_app.Batch', verbose_name='Pozycje')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.branch', verbose_name='Klient')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_app.invoice', verbose_name='Faktura')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.order', verbose_name='Zamówienie'),
        ),
        migrations.AddField(
            model_name='branch',
            name='account_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_app.employee', verbose_name='Opiekun klienta'),
        ),
        migrations.AddField(
            model_name='branch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.client', verbose_name='Klient'),
        ),
        migrations.AddField(
            model_name='batch',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.variant', verbose_name='Produkt'),
        ),
    ]
