# Generated by Django 3.2.9 on 2021-12-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Miejscowość; ')),
                ('street', models.CharField(max_length=64, verbose_name='Ulica: ')),
                ('building_number', models.CharField(max_length=8, verbose_name='Numer budynku: ')),
                ('apartment_number', models.CharField(max_length=8, null=True, verbose_name='Numer lokalu: ')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('type', models.IntegerField(choices=[(1, 'Adres korespondencyjny'), (2, 'Adres Rejestracyjny')], verbose_name='rodzaj adresu')),
                ('details', models.TextField(null=True, verbose_name='Szczególne informacje: ')),
                ('name_of_branch', models.CharField(max_length=60, null=True, verbose_name='Nazwa oddziału: ')),
                ('visit_days', models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], verbose_name='Wizyty w dni tygodnia: ')),
                ('visit_hour_from', models.TimeField(null=True, verbose_name='Wizyty od godziny: ')),
                ('visit_hour_to', models.TimeField(null=True, verbose_name='Wizyty do godziny: ')),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='photo_10',
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(1, 'Apteka sieciowa'), (2, 'Apteka rodzinna')], default=2, verbose_name='Rodzaj apteki: '),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Zamówienie przyjęte, oczekuje na weryfikację.'), (2, 'Zamówienie zmienione, oczekuje na potwierdzenie.'), (3, 'Potwierdzono zamówienie, przekazano do realizacji.'), (4, 'Skompletowane, oczekuje na kuriera.'), (5, 'Problem z zamówniem. Konieczność wyjaśnienia.'), (6, 'Przekazano kurierowi.'), (7, 'Oczekiwanie na płatność'), (8, 'Zakończone.')], default=1, verbose_name='Status zamówienia: '),
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.AddField(
            model_name='branch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.client', verbose_name='Klient: '),
        ),
    ]
