# Generated by Django 3.2.9 on 2021-12-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20211206_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(null=True, upload_to='img/client/logo/'),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_10',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 10: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 2: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 3: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 4: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 5: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_6',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 6: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_7',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 7: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_8',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 8: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_9',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie 9: '),
        ),
        migrations.AddField(
            model_name='variant',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie główne: '),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data wizyty: ')),
                ('visited', models.BooleanField(default=False, verbose_name='Wizyta wykonana: ')),
                ('proof_img', models.ImageField(upload_to='img/visits/', verbose_name='Zdjęcie apteki: ')),
                ('note', models.TextField(verbose_name='Notatka handlowca: ')),
                ('client_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.branch', verbose_name='Klient: ')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.employee', verbose_name='Handlowiec: ')),
            ],
        ),
    ]
