# Generated by Django 3.2.9 on 2021-12-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20211210_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Zamówienie w trakcie tworzenia.'), (1, 'Zamówienie przyjęte, oczekuje na weryfikację.'), (2, 'Zamówienie oczekuje na płatność'), (3, 'Potwierdzono zamówienie, przekazano do realizacji.'), (4, 'Skompletowane, oczekuje na kuriera.'), (5, 'Problem z zamówniem. Konieczność wyjaśnienia.'), (6, 'Przekazano kurierowi.'), (7, 'Oczekiwanie na płatność'), (8, 'Zakończone.')], default=0, verbose_name='Status zamówienia'),
        ),
    ]
