# Generated by Django 3.2.9 on 2021-12-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_auto_20211210_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Zatrudniony'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Stanowisko kierownicze'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='visit_days',
            field=models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (7, 'Niedziela')], verbose_name='Wizyty w dni tygodnia'),
        ),
    ]
