# Generated by Django 3.2.9 on 2021-12-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_auto_20211211_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarsupervisor',
            old_name='date',
            new_name='meeting_date',
        ),
    ]
