# Generated by Django 3.2.9 on 2021-12-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_rename_employee2_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='account_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_app.employee', verbose_name='Opiekun klienta'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ean',
            field=models.IntegerField(verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiration_date',
            field=models.DateField(verbose_name='data Przydatności do użycia'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='netto',
            field=models.FloatField(verbose_name='cena netto'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.CharField(max_length=8, verbose_name='numer Partii'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.IntegerField(verbose_name='Ilość produktów'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.variant', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='vat',
            field=models.IntegerField(choices=[(1, '0.08'), (2, '0.23')], verbose_name='Starka podatku vat'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='apartment_number',
            field=models.CharField(max_length=8, null=True, verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='building_number',
            field=models.CharField(max_length=8, verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='details',
            field=models.TextField(null=True, verbose_name='Szczególne informacje'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_of_branch',
            field=models.CharField(max_length=60, null=True, verbose_name='Nazwa oddziału'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='visit_days',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], verbose_name='Wizyty w dni tygodnia'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='visit_hour_from',
            field=models.TimeField(null=True, verbose_name='Wizyty od godziny'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='visit_hour_to',
            field=models.TimeField(null=True, verbose_name='Wizyty do godziny'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=128, verbose_name='Nazwa firmy'),
        ),
        migrations.AlterField(
            model_name='client',
            name='krs',
            field=models.IntegerField(null=True, verbose_name='Numer KRS'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/img/client/logo/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.IntegerField(verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='regon',
            field=models.IntegerField(verbose_name='REGON'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(1, 'Apteka sieciowa'), (2, 'Apteka rodzinna')], default=2, verbose_name='Rodzaj apteki'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=128, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_app.employee', verbose_name='Przełożony'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data wystawienia'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=32, verbose_name='Numer Faktury'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(verbose_name='Termin płatności'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'Opłacona'), (2, 'Nieopłacona'), (3, 'Po terminie')], verbose_name='Status płatności'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(verbose_name='Zniżka'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_app.invoice', verbose_name='Faktura'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=32, verbose_name='Numer zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Zamówienie przyjęte, oczekuje na weryfikację.'), (2, 'Zamówienie zmienione, oczekuje na potwierdzenie.'), (3, 'Potwierdzono zamówienie, przekazano do realizacji.'), (4, 'Skompletowane, oczekuje na kuriera.'), (5, 'Problem z zamówniem. Konieczność wyjaśnienia.'), (6, 'Przekazano kurierowi.'), (7, 'Oczekiwanie na płatność'), (8, 'Zakończone.')], default=1, verbose_name='Status zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='variant',
            field=models.ManyToManyField(related_name='order', to='manager_app.Variant', verbose_name='Pozycje'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='dose',
            field=models.IntegerField(verbose_name='Dawka'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='next_delivery',
            field=models.DateField(null=True, verbose_name='Planowana data następnej dostawy'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_10',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 10'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 2'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 3'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 4'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 5'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_6',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 6'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_7',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 7'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_8',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 8'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_9',
            field=models.ImageField(null=True, upload_to='media/img/products/', verbose_name='Zdjęcie 9'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='img/products/', verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='unit',
            field=models.IntegerField(choices=[(1, 'mg'), (2, 'ml')], verbose_name='Jednostka(dawki)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='client_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.branch', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data wizyty'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='note',
            field=models.TextField(verbose_name='Notatka handlowca'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='proof_img',
            field=models.ImageField(upload_to='static/img/client/visits/', verbose_name='Zdjęcie apteki'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager_app.employee', verbose_name='Handlowiec'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited',
            field=models.BooleanField(default=False, verbose_name='Wizyta wykonana'),
        ),
    ]
