# Generated by Django 3.2.9 on 2021-12-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_rename_date_calendarsupervisor_meeting_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
