# Generated by Django 3.2.9 on 2021-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_auto_20211208_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='W sprzedaży'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='W sprzedaży'),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='W sprzedaży'),
        ),
    ]
