# Generated by Django 3.2.9 on 2021-12-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_delete_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='short_company_name',
            field=models.CharField(max_length=16, null=True, verbose_name='Skrócona nazwa'),
        ),
    ]
