# Generated by Django 3.2.9 on 2021-12-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0008_client_short_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.IntegerField(choices=[(1, 'Adres korespondencyjny'), (2, 'Adres Rejestracyjny')], default=1, verbose_name='rodzaj adresu'),
        ),
    ]
