# Generated by Django 3.2.9 on 2021-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0010_alter_client_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='visit_hour_from',
            field=models.TimeField(default='08:00:00', null=True, verbose_name='Wizyty od godziny'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='visit_hour_to',
            field=models.TimeField(default='16:00:00', null=True, verbose_name='Wizyty do godziny'),
        ),
    ]
