# Generated by Django 3.2.9 on 2021-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0011_auto_20211215_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='ean',
            field=models.BigIntegerField(verbose_name='EAN'),
        ),
    ]
